export type MyPreferences = {
  SETTINGS: {
    // INBOX
    INBOX_SHOW_BUTTON_SYNC: boolean
    INBOX_SHOW_BUTTON_SEARCH: boolean
    INBOX_SHOW_BUTTON_UN_READ: boolean
    INBOX_SHOW_BUTTON_REMOVE: boolean
    INBOX_SHOW_BUTTON_ARCHIVE: boolean
    INBOX_CONFIRM_BEFORE_SENT: boolean
    INBOX_CONFIRM_BEFORE_FILING: boolean
    INBOX_CONFIRM_BEFORE_REMOVING: boolean
    // SENT
    SENT_SHOW_BUTTON_SEARCH: boolean
    // GENERAL
    GENERAL_SHOW_BUTTON_PURGE: boolean
    GENERAL_INITIALIZE_DATABASE: boolean
    GENERAL_CONFIRM_PURGE_DATABASE: boolean
  }
}
