export let SHARED_PREFERENCES = {
  SETTINGS: {
    // INBOX
    INBOX_SHOW_BUTTON_STARRED: true,
    INBOX_SHOW_BUTTON_SYNC: true,
    INBOX_SHOW_BUTTON_SEARCH: true,
    INBOX_SHOW_BUTTON_UN_READ: true,
    INBOX_SHOW_BUTTON_REMOVE: false,
    INBOX_SHOW_BUTTON_ARCHIVE: false,
    INBOX_CONFIRM_BEFORE_SENT: false,
    INBOX_CONFIRM_BEFORE_FILING: true,
    INBOX_CONFIRM_BEFORE_REMOVING: true,
    // SENT
    SENT_SHOW_BUTTON_SEARCH: true,
    // STARRED
    STARRED_SHOW_BUTTON_SEARCH: true,
    // GENERAL
    GENERAL_SHOW_BUTTON_PURGE: false,
    GENERAL_INITIALIZE_DATABASE: true,
    GENERAL_CONFIRM_PURGE_DATABASE: true,
  },
}
